name: delete-older-workflow
on:
  workflow_dispatch:
  schedule:
    - cron: 30 */12 * * *

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
    
    - name: 删除工作流
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 3
        keep_minimum_runs: 0
