name: Merge-upstream-lede

on:
  push:
    paths:
      - '.github/diy/lede.sh'
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started
  repository_dispatch:

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    runs-on: Ubuntu-20.04
    
    name: Update ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [lede]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Initialization environment
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x .github/diy/${{matrix.target}}.sh
        chmod +x .github/diy/convert_translation.sh
        git clone -b ${{matrix.target}} https://github.com/moruiris/openwrt-packages.git ${{matrix.target}}
        cd ${{matrix.target}}
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf * >/dev/null 2>&1
        $GITHUB_WORKSPACE/.github/diy/${{matrix.target}}.sh
        $GITHUB_WORKSPACE/.github/diy/convert_translation.sh
        
    - name: Upload
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        cd $GITHUB_WORKSPACE/${{matrix.target}}
        git add .
        git commit -am "update $(date +%Y-%m-%d" "%H:%M:%S)"
        git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/moruiris/openwrt-packages.git" HEAD:${{matrix.target}}
